import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  systemDesign: [{ type: "autogenerated", dirName: "system-design" }],
  reference: [{ type: "autogenerated", dirName: "reference" }],
};

export default sidebars;
